import { buildDomain } from "./_build";

const data = {
  slug: "healthcare",
  label: "Healthcare Clinics & Hospitals",
  audience: "clinic owners, hospital admins & medical directors",
  heroIcon: "Stethoscope",
  headline: "Your doctors went to med school for ten years. They're spending six hours a day on paperwork.",
  subheadline:
    "From appointment chaos to discharge summaries to insurance pre-auth — most of the admin burden in Indian healthcare is now an AI workflow. Below are 15 places where I take work off doctors, nurses and the front desk, with the actual rupee impact.",
  chips: ["Appointments", "Voice EMR", "Discharge summaries", "Pre-auth", "Patient follow-up"],
  palette: { c1: "#14B8A6", c2: "#06B6D4", accent: "#F97373" },
  assumedRate: 600,
  buildCost: 350000,
  monthlyRun: 14000,
  painHeadline:
    "Patients waiting. Doctors typing. Insurance bouncing. Nobody is actually doing medicine.",
  painPoints: [
    "Front desk drowning in WhatsApp + phone + walk-in appointment requests with no single calendar.",
    "Doctors typing notes till 10 PM instead of seeing one more patient — or going home to family.",
    "Discharge summaries delayed by 2 days, beds blocked, new admissions waiting.",
    "Insurance pre-authorisation takes 4–6 hours per case because forms get retyped 3 times.",
    "Patient follow-ups (medication, reports, recall) silently dropped — preventable revenue lost.",
    "Inventory of consumables and pharmacy items is on Excel; expiry losses every month.",
  ],
  tasks: [
    {
      icon: "CalendarClock",
      tag: "Front desk",
      title: "Appointment booking across phone, WA, web & walk-ins",
      traditional: {
        how: "Receptionist juggles landline, two WhatsApp numbers, walk-ins, and a paper register.",
        timeText: "3 min × 90 bookings/day",
        volumeText: "≈ 2,300 bookings / month",
        hoursPerMonth: 115,
      },
      ai: {
        how: "AI receptionist on WA + IVR + website books, reschedules, sends reminders, even handles cancellations and waitlist promotion.",
        timeText: "instant",
        humanLoop: "Front desk handles edge cases",
        hoursPerMonth: 22,
        toolCost: 7500,
      },
      feels: "No-shows drop 30%. Patients stop saying 'nobody picked the phone'.",
    },
    {
      icon: "Mic",
      tag: "Voice EMR",
      title: "Doctor consultation notes & prescriptions",
      traditional: {
        how: "Doctor types into EMR or scribbles paper, then a clerk re-enters at end of day.",
        timeText: "5 min × 35 patients/day",
        volumeText: "≈ 900 visits / month",
        hoursPerMonth: 75,
      },
      ai: {
        how: "Ambient voice scribe listens to consultation, drafts SOAP note + Rx + ICD code in Hindi/English; doctor edits 1–2 lines and signs.",
        timeText: "1 min × 900 visits",
        humanLoop: "Doctor signs every note",
        hoursPerMonth: 15,
        toolCost: 9000,
      },
      feels: "Doctor finally leaves OPD on time. They actually look at the patient instead of the screen.",
    },
    {
      icon: "FileText",
      tag: "Discharge",
      title: "Discharge summary creation",
      traditional: {
        how: "Resident copy-pastes from admission notes, lab results, vitals, scribbled progress notes — into a Word template.",
        timeText: "45 min × 12 discharges/day",
        volumeText: "≈ 320 / month",
        hoursPerMonth: 240,
      },
      ai: {
        how: "Agent reads EMR, vitals, lab, OT notes, drafts a structured discharge summary; doctor edits in 5 min.",
        timeText: "5 min × 320",
        humanLoop: "Doctor signs",
        hoursPerMonth: 27,
        toolCost: 6500,
      },
      feels: "Beds turn over faster. ALOS drops, capacity grows without adding rooms.",
    },
    {
      icon: "ShieldPlus",
      tag: "Insurance",
      title: "TPA pre-authorisation packets",
      traditional: {
        how: "Insurance desk fills 6 forms, attaches Rx, indoor papers, ICD codes, sends fax / portal upload, follows up.",
        timeText: "75 min × 12 cases/day",
        volumeText: "≈ 320 cases / month",
        hoursPerMonth: 400,
      },
      ai: {
        how: "Agent reads EMR + indoor file + treatment plan, fills TPA form, attaches docs, submits to portal; tracks query responses.",
        timeText: "8 min × 320",
        humanLoop: "Insurance officer reviews",
        hoursPerMonth: 43,
        toolCost: 8500,
      },
      feels: "Pre-auth approvals come in same-day. Patients stop being held hostage at the cashier.",
    },
    {
      icon: "PhoneCall",
      tag: "Recall",
      title: "Patient follow-up & recall calls",
      traditional: {
        how: "Junior calls discharged/visited patients to check on medication, schedule follow-up, push tests.",
        timeText: "4 min × 50 calls/day",
        volumeText: "≈ 1,300 / month",
        hoursPerMonth: 87,
      },
      ai: {
        how: "Voice + WA agent calls in regional language, asks scripted health questions, books follow-up if needed, raises red flags to clinician.",
        timeText: "auto",
        humanLoop: "Red flags routed to nurse",
        hoursPerMonth: 12,
        toolCost: 5500,
      },
      feels: "Repeat-visit revenue grows without adding marketing spend. Outcomes also improve.",
    },
    {
      icon: "ClipboardList",
      tag: "Triage",
      title: "Symptom triage before the visit",
      traditional: {
        how: "Receptionist asks 'what's the problem?', books any available doctor — wrong specialty, wasted slot.",
        timeText: "2 min × 90 bookings/day",
        volumeText: "≈ 2,300 / month",
        hoursPerMonth: 77,
      },
      ai: {
        how: "Pre-visit chat asks symptom, duration, red flags; routes to right specialty; emergencies escalated to phone.",
        timeText: "auto",
        humanLoop: "Front desk confirms",
        hoursPerMonth: 12,
        toolCost: 4000,
      },
      feels: "Doctors see the right patients. OPD throughput rises without hiring.",
    },
    {
      icon: "TestTube",
      tag: "Reports",
      title: "Lab/radiology report dispatch & explanation",
      traditional: {
        how: "Report ready → clerk emails/prints → patient calls to ask 'what does this mean?' → doctor explains again.",
        timeText: "6 min × 80 reports/day",
        volumeText: "≈ 2,000 / month",
        hoursPerMonth: 200,
      },
      ai: {
        how: "Reports auto-sent on WA with a plain-language summary; if abnormal, agent books follow-up and informs the doctor.",
        timeText: "auto",
        humanLoop: "Critical values to doctor",
        hoursPerMonth: 22,
        toolCost: 4500,
      },
      feels: "Patients feel cared for, not just billed. Critical findings don't slip through.",
    },
    {
      icon: "Pill",
      tag: "Pharmacy",
      title: "Pharmacy stock, expiry & reorder",
      traditional: {
        how: "Pharmacist counts, checks expiry, raises POs in Excel; expiry losses common.",
        timeText: "20 hrs / month",
        volumeText: "1 in-house pharmacy",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Inventory model forecasts demand, alerts on slow movers near expiry, drafts POs to distributor.",
        timeText: "auto",
        humanLoop: "Pharmacist approves PO",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Expiry write-offs nearly disappear. Stock-outs of fast movers also stop.",
    },
    {
      icon: "FileScan",
      tag: "Old records",
      title: "Digitising paper case files & old prescriptions",
      traditional: {
        how: "Data entry person types decades of paper notes into EMR — slow, error-prone, never finished.",
        timeText: "1 person × 8 hrs × 25 days",
        volumeText: "ongoing",
        hoursPerMonth: 200,
      },
      ai: {
        how: "Vision LLM reads handwritten Rx, lab reports, discharge papers; structures into EMR; flags illegible items for human.",
        timeText: "auto",
        humanLoop: "Operator reviews flagged items",
        hoursPerMonth: 25,
        toolCost: 5000,
      },
      feels: "Years of paper become a searchable patient history overnight.",
    },
    {
      icon: "AlertCircle",
      tag: "Quality",
      title: "Hospital quality & infection-control reporting",
      traditional: {
        how: "Quality team manually fills NABH/HCO sheets each month from chart audits.",
        timeText: "30 hrs / month",
        volumeText: "audit cycle",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Agent walks through EMR & nursing notes, computes indicators (HAI, falls, re-admissions), drafts the monthly report.",
        timeText: "auto",
        humanLoop: "Quality head reviews",
        hoursPerMonth: 5,
        toolCost: 2800,
      },
      feels: "NABH cycles stop being a fire drill. Real quality issues surface in real time.",
    },
    {
      icon: "Wallet",
      tag: "Billing",
      title: "Inpatient billing & queries at discharge",
      traditional: {
        how: "Billing clerk pulls every charge from OT, ICU, pharmacy, lab; explains line items to family.",
        timeText: "55 min × 12 IP discharges/day",
        volumeText: "≈ 320 / month",
        hoursPerMonth: 293,
      },
      ai: {
        how: "Auto-aggregated bill with plain-language line items; AI explains charges to family on WA before discharge.",
        timeText: "8 min × 320",
        humanLoop: "Billing supervisor signs",
        hoursPerMonth: 43,
        toolCost: 6000,
      },
      feels: "Discharge time falls from 6 hrs to under 2. Online reviews quietly improve.",
    },
    {
      icon: "Star",
      tag: "Reviews",
      title: "Online reputation & review responses",
      traditional: {
        how: "Marketing replies on Google, Practo, Justdial reviews — usually slow and templated.",
        timeText: "10 hrs / month",
        volumeText: "150 reviews",
        hoursPerMonth: 10,
      },
      ai: {
        how: "Agent monitors review platforms, drafts personalised responses citing the visit context, escalates real complaints.",
        timeText: "auto + 1 hr review",
        humanLoop: "Marketing approves negative replies",
        hoursPerMonth: 1.5,
        toolCost: 1800,
      },
      feels: "Rating ticks up. New patient inquiries increase without ads.",
    },
    {
      icon: "Megaphone",
      tag: "Outreach",
      title: "Health camps, screening campaigns, recall drives",
      traditional: {
        how: "Marketing builds lists in Excel, sends SMS blasts; tracking near zero.",
        timeText: "16 hrs / month",
        volumeText: "2 campaigns",
        hoursPerMonth: 16,
      },
      ai: {
        how: "Segmented WA campaigns based on age, condition, last visit; bot answers FAQs and books slots directly.",
        timeText: "auto",
        humanLoop: "Marketing reviews creative",
        hoursPerMonth: 3,
        toolCost: 2500,
      },
      feels: "Camps actually fill. ROI per campaign becomes measurable.",
    },
    {
      icon: "BookOpenCheck",
      tag: "Doctor knowledge",
      title: "Internal protocol & guideline lookup for staff",
      traditional: {
        how: "Junior doctors call seniors at night to confirm protocols; seniors lose sleep.",
        timeText: "scattered ≈ 25 hrs / month",
        volumeText: "across staff",
        hoursPerMonth: 25,
      },
      ai: {
        how: "RAG bot trained on hospital SOPs, drug formulary, clinical guidelines — answers cited and traceable.",
        timeText: "instant",
        humanLoop: "Seniors only for true edge cases",
        hoursPerMonth: 4,
        toolCost: 2200,
      },
      feels: "Night-shift quality stops depending on which junior is on duty.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Doctor-wise, department-wise P&L weekly",
      traditional: {
        how: "Finance pulls HMS exports into Excel; medical director reads on Friday.",
        timeText: "10 hrs / week",
        volumeText: "4 weeks",
        hoursPerMonth: 40,
      },
      ai: {
        how: "Live dashboard with per-doctor occupancy, IP/OP mix, payer mix, no-show rate, conversion to surgery.",
        timeText: "auto",
        humanLoop: "Director reviews & acts",
        hoursPerMonth: 5,
        toolCost: 3000,
      },
      feels: "You stop running the hospital on month-end shocks. You see leaks weekly.",
    },
  ],
};

export default buildDomain(data);
