/**
 * Lightweight metadata index for all 22 domain landing pages.
 * Used by the homepage AIForBusiness section so we don't bundle
 * every domain's full task list into the marketing page.
 */
export const DOMAIN_INDEX = [
  {
    slug: "logistics-freight",
    label: "Logistics & Freight",
    heroIcon: "Truck",
    audience: "fleet owners, brokers & 3PLs",
    palette: { c1: "#2563EB", c2: "#F59E0B", accent: "#0EA5E9" },
    oneLiner: "From dispatch to detention claims, AI compresses freight ops from days to minutes.",
  },
  {
    slug: "healthcare",
    label: "Healthcare & Clinics",
    heroIcon: "Stethoscope",
    audience: "hospitals, clinics & diagnostic chains",
    palette: { c1: "#0EA5E9", c2: "#10B981", accent: "#F472B6" },
    oneLiner: "Front-desk to insurance to follow-ups — clinicians get back to patients.",
  },
  {
    slug: "retail-ecommerce",
    label: "Retail & E-commerce",
    heroIcon: "ShoppingBag",
    audience: "D2C founders, retailers & marketplace sellers",
    palette: { c1: "#EC4899", c2: "#8B5CF6", accent: "#FACC15" },
    oneLiner: "Listings, support, returns, marketing — your team focuses on growth, not tickets.",
  },
  {
    slug: "manufacturing",
    label: "Manufacturing & MSMEs",
    heroIcon: "Factory",
    audience: "plant heads, MSME owners & operations leaders",
    palette: { c1: "#F97316", c2: "#0EA5E9", accent: "#84CC16" },
    oneLiner: "From shop-floor to shipping — AI takes the paper out of Indian manufacturing.",
  },
  {
    slug: "construction-engineering",
    label: "Construction & Engineering",
    heroIcon: "HardHat",
    audience: "EPC firms, contractors & project owners",
    palette: { c1: "#EAB308", c2: "#1F2937", accent: "#F97316" },
    oneLiner: "Tenders, BOQs, RA bills, site reports — site spends time building, not typing.",
  },
  {
    slug: "insurance",
    label: "Insurance",
    heroIcon: "Umbrella",
    audience: "insurers, broking houses & InsurTech ops",
    palette: { c1: "#7C3AED", c2: "#06B6D4", accent: "#FB923C" },
    oneLiner: "Underwriting, claims, renewals — same workforce serves 5× the policies.",
  },
  {
    slug: "banking-capital-markets",
    label: "Banking & Capital Markets",
    heroIcon: "Landmark",
    audience: "private banks, NBFCs & wealth platforms",
    palette: { c1: "#1D4ED8", c2: "#10B981", accent: "#F59E0B" },
    oneLiner: "KYC to credit decisioning to RM productivity — AI in the back office.",
  },
  {
    slug: "accounting-finance-ops",
    label: "Accounting & Finance Ops",
    heroIcon: "Calculator",
    audience: "CA firms, finance teams & controllers",
    palette: { c1: "#0F766E", c2: "#9333EA", accent: "#FBBF24" },
    oneLiner: "Bookkeeping, AP, GST, audit — your CAs do advisory, not data entry.",
  },
  {
    slug: "legal",
    label: "Legal & Law Firms",
    heroIcon: "Scale",
    audience: "law firms, in-house counsel & boutique practices",
    palette: { c1: "#1E293B", c2: "#B45309", accent: "#94A3B8" },
    oneLiner: "Drafting, due diligence, court tracking — partners focus on advocacy.",
  },
  {
    slug: "real-estate",
    label: "Real Estate & Property",
    heroIcon: "Building2",
    audience: "developers, brokers & property managers",
    palette: { c1: "#84CC16", c2: "#0D9488", accent: "#C2410C" },
    oneLiner: "Lead-to-booking-to-handover — leads don't die in your call team's WhatsApp.",
  },
  {
    slug: "education-coaching",
    label: "Education & Coaching",
    heroIcon: "GraduationCap",
    audience: "schools, coaching institutes & ed-tech founders",
    palette: { c1: "#7C3AED", c2: "#0EA5E9", accent: "#F59E0B" },
    oneLiner: "Admissions, doubts, grading, parent comms — teachers actually teach.",
  },
  {
    slug: "hr-recruitment",
    label: "HR & Recruitment",
    heroIcon: "Users",
    audience: "TA leads, HRBPs & people-ops heads",
    palette: { c1: "#E11D48", c2: "#0D9488", accent: "#F59E0B" },
    oneLiner: "Sourcing to onboarding to engagement — recruiters do recruiting, not screening.",
  },
  {
    slug: "telecom-isp",
    label: "Telecom & ISP",
    heroIcon: "Radio",
    audience: "ISPs, telecom NOCs & enterprise connectivity",
    palette: { c1: "#06B6D4", c2: "#7C3AED", accent: "#F59E0B" },
    oneLiner: "Customer chat, NOC alarms, SLA reports — small ops team, carrier-grade service.",
  },
  {
    slug: "government-public-sector",
    label: "Government & Public Sector",
    heroIcon: "Landmark",
    audience: "municipal corps, PSUs & e-governance teams",
    palette: { c1: "#1E3A8A", c2: "#F97316", accent: "#FDE68A" },
    oneLiner: "Citizens get answers in their language, in seconds, at 11 PM.",
  },
  {
    slug: "travel-tourism-hospitality",
    label: "Travel & Hospitality",
    heroIcon: "Plane",
    audience: "DMCs, hotels, OTAs & tour operators",
    palette: { c1: "#0D9488", c2: "#FB7185", accent: "#FBBF24" },
    oneLiner: "Itinerary to concierge to refunds — guests feel cared for, team gets sundays.",
  },
  {
    slug: "restaurants-food-services",
    label: "Restaurants & Food",
    heroIcon: "UtensilsCrossed",
    audience: "QSRs, cloud kitchens & cafe chains",
    palette: { c1: "#DC2626", c2: "#FBBF24", accent: "#16A34A" },
    oneLiner: "Aggregator ops, inventory, loyalty, P&L — kitchen focuses on the food.",
  },
  {
    slug: "agriculture-agribusiness",
    label: "Agriculture & Agribusiness",
    heroIcon: "Sprout",
    audience: "FPOs, agri input cos & agritech",
    palette: { c1: "#16A34A", c2: "#CA8A04", accent: "#78350F" },
    oneLiner: "Advisory, mandi prices, procurement — farmer trust + FPO scale.",
  },
  {
    slug: "renewable-energy",
    label: "Renewable Energy & Solar",
    heroIcon: "Sun",
    audience: "solar EPCs, IPPs & energy consultants",
    palette: { c1: "#14B8A6", c2: "#84CC16", accent: "#F59E0B" },
    oneLiner: "Subsidies and DISCOM apps stop being the bottleneck.",
  },
  {
    slug: "customer-support-bpo",
    label: "Customer Support & BPO",
    heroIcon: "Headphones",
    audience: "BPO leaders, CX heads & success teams",
    palette: { c1: "#2563EB", c2: "#14B8A6", accent: "#F59E0B" },
    oneLiner: "Voice agents, 100% QA, agent assist — 100 seats deliver 1,000-seat quality.",
  },
  {
    slug: "professional-services-agencies",
    label: "Professional Services & Agencies",
    heroIcon: "Briefcase",
    audience: "consulting, agencies & boutique studios",
    palette: { c1: "#1F2937", c2: "#4F46E5", accent: "#D4AF37" },
    oneLiner: "Proposals, decks, status, time-sheets — seniors do senior work.",
  },
  {
    slug: "mortgage-lenders-brokers",
    label: "Mortgage Lenders & Brokers",
    heroIcon: "Home",
    audience: "HFCs, NBFCs, DSAs & broker shops",
    palette: { c1: "#166534", c2: "#B45309", accent: "#FDE68A" },
    oneLiner: "Doc collection to sanction packets in days, not weeks.",
  },
  {
    slug: "truck-permit-providers",
    label: "Truck Permit & Escort (USA)",
    heroIcon: "FileBadge",
    audience: "OS/OW permit shops & escort coordinators",
    palette: { c1: "#F59E0B", c2: "#1E3A8A", accent: "#F97316" },
    oneLiner: "BOL → multi-state permits → escort dispatch, end-to-end.",
  },
];
