import { buildDomain } from "./_build";

const data = {
  slug: "insurance",
  label: "Insurance",
  audience: "insurers, brokers & TPA operations leads",
  heroIcon: "Umbrella",
  headline: "Underwriters, agents and claims handlers are doing data-entry work. AI gives them their judgement back.",
  subheadline:
    "Quotation, KYC, document checks, claim FNOL, fraud screening, renewals — almost every node in an insurance ops chain has 30-60% busywork. Below are 15 places I take that work off the team, and the rupees that fall to the bottom line.",
  chips: ["Quote intelligence", "Claims FNOL bot", "Document AI", "Fraud signals", "Renewals"],
  palette: { c1: "#1E3A8A", c2: "#0EA5E9", accent: "#F59E0B" },
  assumedRate: 550,
  buildCost: 380000,
  monthlyRun: 14000,
  painHeadline:
    "Your best underwriter spends half their day re-keying KYC and matching policy schedules. That is not what you hired them for.",
  painPoints: [
    "Lead-to-quote takes hours because data is keyed across 5 portals.",
    "Claim FNOL still happens by phone & email; first 24 hours wasted.",
    "Document checks (Aadhaar, PAN, driving licence, RC, medical) done manually for every case.",
    "Renewal calls are random — high-value clients lapse silently.",
    "Fraud signals only spotted after payout; recoveries near impossible.",
    "Agents and brokers ask same product questions repeatedly; sales support drowning.",
  ],
  tasks: [
    {
      icon: "Calculator",
      tag: "Quotation",
      title: "Multi-insurer quote generation",
      traditional: {
        how: "Sales puts client info into 4-6 insurer portals, downloads PDFs, builds comparison sheet.",
        timeText: "30 min × 60 quotes/day",
        volumeText: "≈ 1,500 / month",
        hoursPerMonth: 750,
      },
      ai: {
        how: "Agent reads lead, fills insurer portals via API/RPA, builds branded comparison PDF in your template.",
        timeText: "3 min × 1,500",
        humanLoop: "Sales reviews recommendation",
        hoursPerMonth: 75,
        toolCost: 9000,
      },
      feels: "Quote turn-around drops from same-day to under 5 minutes. Conversion climbs.",
    },
    {
      icon: "ScanFace",
      tag: "KYC",
      title: "KYC, video-KYC & document validation",
      traditional: {
        how: "Ops verifies Aadhaar, PAN, address proof, photographs — manual cross-check.",
        timeText: "12 min × 800 cases / month",
        volumeText: "≈ 800",
        hoursPerMonth: 160,
      },
      ai: {
        how: "Vision + liveness model verifies docs, matches face, fetches CKYC, flags fakes.",
        timeText: "30 sec × 800",
        humanLoop: "Compliance reviews flagged",
        hoursPerMonth: 14,
        toolCost: 5500,
      },
      feels: "Onboarding TAT drops from days to minutes. Drop-offs at proposal stage shrink.",
    },
    {
      icon: "PhoneIncoming",
      tag: "FNOL",
      title: "First Notice of Loss intake (motor / health / property)",
      traditional: {
        how: "Customer calls helpdesk, agent fills form, asks 20 questions, raises claim ID.",
        timeText: "15 min × 300 FNOLs / month",
        volumeText: "≈ 300",
        hoursPerMonth: 75,
      },
      ai: {
        how: "WA + IVR voice agent captures FNOL with photos / videos, books surveyor / hospital, generates claim ID instantly.",
        timeText: "auto",
        humanLoop: "Adjuster reviews complex losses",
        hoursPerMonth: 12,
        toolCost: 6500,
      },
      feels: "Customers feel taken care of in the first 5 minutes — when they remember it most.",
    },
    {
      icon: "FileCheck",
      tag: "Claims docs",
      title: "Claim document collection & completeness check",
      traditional: {
        how: "Surveyor / TPA chases customer for missing docs over 4-7 days.",
        timeText: "20 min × 300 claims",
        volumeText: "≈ 300",
        hoursPerMonth: 100,
      },
      ai: {
        how: "Agent guides customer on WA: 'send PUC photo, bills, FIR if any', validates each, only escalates when truly stuck.",
        timeText: "auto + 5 min review",
        humanLoop: "Surveyor reviews packet",
        hoursPerMonth: 18,
        toolCost: 4500,
      },
      feels: "Claim cycle time falls. NPS rises. Repeat business follows.",
    },
    {
      icon: "Microscope",
      tag: "Damage assessment",
      title: "Motor damage estimation from photos",
      traditional: {
        how: "Surveyor visits / customer mails photos, garage gives estimate, surveyor validates manually.",
        timeText: "40 min × 250 motor claims",
        volumeText: "≈ 250",
        hoursPerMonth: 167,
      },
      ai: {
        how: "Vision model analyses damage photos, predicts parts list & labour hours, compares to garage quote.",
        timeText: "5 min × 250",
        humanLoop: "Surveyor signs off",
        hoursPerMonth: 25,
        toolCost: 7500,
      },
      feels: "Motor claims close in 2 days, not 9. Garage padding gets caught.",
    },
    {
      icon: "ShieldAlert",
      tag: "Fraud",
      title: "Fraud signal detection on incoming claims",
      traditional: {
        how: "SIU samples claims; most fraud spotted post-payout.",
        timeText: "60 hrs / month sampling",
        volumeText: "claims",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Pattern model scores every claim on doc tampering, geo-mismatch, repeat parties, doctor-patient nexus.",
        timeText: "auto",
        humanLoop: "SIU investigates top-flagged",
        hoursPerMonth: 12,
        toolCost: 6500,
      },
      feels: "Loss ratio improves. Real fraud rings actually get cracked.",
    },
    {
      icon: "Bell",
      tag: "Renewals",
      title: "Renewal nudges & lapse prevention",
      traditional: {
        how: "Tele-callers call from a list; many high-value renewals slip silently.",
        timeText: "5 min × 60 calls / day",
        volumeText: "≈ 1,500",
        hoursPerMonth: 125,
      },
      ai: {
        how: "Agent sends personalised WA renewal with comparison vs current cover, books call only when needed.",
        timeText: "auto",
        humanLoop: "Tele-team for fence-sitters",
        hoursPerMonth: 22,
        toolCost: 5000,
      },
      feels: "Renewal retention climbs 6-10 points. The compounding effect is huge.",
    },
    {
      icon: "FileSearch",
      tag: "Underwriting",
      title: "Risk underwriting from medicals / property reports",
      traditional: {
        how: "UW reads PPMC, medical, property survey, builds risk score manually.",
        timeText: "40 min × 200 cases",
        volumeText: "≈ 200",
        hoursPerMonth: 133,
      },
      ai: {
        how: "Agent extracts medical history, BMI, BP, lipid, family history; suggests rating with reasons.",
        timeText: "5 min × 200",
        humanLoop: "UW signs every case",
        hoursPerMonth: 17,
        toolCost: 6500,
      },
      feels: "UW's day shifts from data entry to actual judgement on edge cases.",
    },
    {
      icon: "Mail",
      tag: "Agent comms",
      title: "Agent / broker support helpdesk",
      traditional: {
        how: "Agents call sales support for product, premium, commission queries.",
        timeText: "5 min × 250 queries / day",
        volumeText: "≈ 6,300 / month",
        hoursPerMonth: 525,
      },
      ai: {
        how: "Bot answers product, premium, commission, claim-status queries instantly with cited policy wordings.",
        timeText: "instant",
        humanLoop: "Humans for nuance",
        hoursPerMonth: 80,
        toolCost: 7500,
      },
      feels: "Agents stop quitting because nobody answers their basic questions.",
    },
    {
      icon: "MessageCircle",
      tag: "Customer chat",
      title: "Policyholder service — endorsements, NACH, statements",
      traditional: {
        how: "CSR handles endorsements, NACH issues, premium receipts manually.",
        timeText: "4 min × 200 / day",
        volumeText: "≈ 5,000",
        hoursPerMonth: 333,
      },
      ai: {
        how: "WA + chat bot processes endorsements, NACH retries, statements; routes only complex cases.",
        timeText: "auto",
        humanLoop: "Humans for grievances",
        hoursPerMonth: 50,
        toolCost: 5500,
      },
      feels: "Service complaints to IRDAI fall sharply.",
    },
    {
      icon: "Workflow",
      tag: "Reconciliation",
      title: "Premium & commission reconciliation",
      traditional: {
        how: "Finance matches premium received vs policy issued, brokers' commission settled monthly.",
        timeText: "120 hrs / month",
        volumeText: "across products",
        hoursPerMonth: 120,
      },
      ai: {
        how: "Reconciliation engine matches premium ↔ policy ↔ bank credit ↔ broker commission with explainable mismatches.",
        timeText: "auto",
        humanLoop: "Finance investigates exceptions",
        hoursPerMonth: 18,
        toolCost: 5000,
      },
      feels: "Month-end closes in 2 days. Brokers stop disputing every commission cheque.",
    },
    {
      icon: "Gavel",
      tag: "Grievance",
      title: "IRDAI grievance & ombudsman response drafting",
      traditional: {
        how: "Legal team drafts replies referencing policy clauses, claim history, surveyor reports.",
        timeText: "3 hrs × 30 / month",
        volumeText: "≈ 30",
        hoursPerMonth: 90,
      },
      ai: {
        how: "Agent drafts response with citations from policy wording, repudiation reasons, evidence; legal reviews.",
        timeText: "30 min × 30",
        humanLoop: "Legal signs off",
        hoursPerMonth: 15,
        toolCost: 3500,
      },
      feels: "Grievances close faster. Adverse outcomes fall.",
    },
    {
      icon: "BookOpen",
      tag: "Training",
      title: "New agent / employee training & assessment",
      traditional: {
        how: "Trainer runs 5-day classroom batches monthly; assessments paper-based.",
        timeText: "60 hrs / month",
        volumeText: "1 trainer",
        hoursPerMonth: 60,
      },
      ai: {
        how: "AI tutor + role-play simulator with adaptive content + auto assessment & certification.",
        timeText: "auto + 6 hr review",
        humanLoop: "Trainer audits",
        hoursPerMonth: 8,
        toolCost: 5000,
      },
      feels: "Agents start selling in week 2 instead of week 5.",
    },
    {
      icon: "Sparkles",
      tag: "Cross-sell",
      title: "Cross-sell & up-sell to existing book",
      traditional: {
        how: "Marketing sends generic offers; conversion under 1%.",
        timeText: "30 hrs / month",
        volumeText: "campaigns",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Model identifies gaps in client cover (no health, only motor), drafts personalised pitch, books call.",
        timeText: "auto",
        humanLoop: "Sales closes",
        hoursPerMonth: 5,
        toolCost: 4000,
      },
      feels: "ARPU per customer climbs. Existing book becomes your cheapest growth channel.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Daily ops & risk dashboard for COO",
      traditional: {
        how: "MIS pulls reports; COO sees yesterday by tomorrow EOD.",
        timeText: "40 hrs / month",
        volumeText: "MIS",
        hoursPerMonth: 40,
      },
      ai: {
        how: "Live dashboard: NB, renewal, claims TAT, loss ratio, fraud queue, NPS — daily WA digest to COO.",
        timeText: "auto",
        humanLoop: "COO acts",
        hoursPerMonth: 6,
        toolCost: 3500,
      },
      feels: "COO leads with data, not anecdotes.",
    },
  ],
};

export default buildDomain(data);
