import { buildDomain } from "./_build";

const data = {
  slug: "legal",
  label: "Legal & In-house Legal Teams",
  audience: "law firms, GCs & in-house counsel",
  heroIcon: "Scale",
  headline: "You charge for thinking. You're still spending half the day reading.",
  subheadline:
    "Discovery, due diligence, contract review, drafting, court-list tracking — these chunks of legal work are now agentic. Below are the 15 places I deploy AI for Indian law firms and corporate legal teams, with the billable hours you protect.",
  chips: ["Contract review", "Due diligence", "Court tracking", "Legal research", "Compliance drafting"],
  palette: { c1: "#7F1D1D", c2: "#B91C1C", accent: "#D4AF37" },
  assumedRate: 1500,
  buildCost: 350000,
  monthlyRun: 13000,
  painHeadline:
    "Your associates didn't go through 5 years of law school to redact 200 NDAs a month.",
  painPoints: [
    "Standard contracts re-drafted from scratch instead of from a playbook.",
    "Due diligence rooms reviewed line by line; weeks lost.",
    "Court listing & order tracking on WhatsApp groups.",
    "Legal research means 4-hour database dives for one judgement.",
    "Compliance calendars in Excel — RBI, SEBI, MCA dates slip.",
    "Time-sheets reconstructed from memory on the 28th.",
  ],
  tasks: [
    {
      icon: "FileSearch",
      tag: "Contract review",
      title: "Contract review against a playbook",
      traditional: {
        how: "Associate reads contract, marks deviations from firm playbook, drafts redlines.",
        timeText: "3 hrs × 60 contracts / month",
        volumeText: "≈ 60",
        hoursPerMonth: 180,
      },
      ai: {
        how: "Agent runs playbook check, drafts redlines, summarises risk in plain language.",
        timeText: "20 min × 60",
        humanLoop: "Associate finalises",
        hoursPerMonth: 20,
        toolCost: 8500,
      },
      feels: "You bill the same hours but for advisory work, not for reading.",
    },
    {
      icon: "PenLine",
      tag: "Drafting",
      title: "First-draft NDAs, MSAs, SOWs, employment letters",
      traditional: {
        how: "Junior draws from old precedents, edits to fit the deal.",
        timeText: "2 hrs × 80 / month",
        volumeText: "≈ 80",
        hoursPerMonth: 160,
      },
      ai: {
        how: "Agent generates first draft from term sheet inputs; junior tightens it.",
        timeText: "20 min × 80",
        humanLoop: "Junior finalises",
        hoursPerMonth: 27,
        toolCost: 5500,
      },
      feels: "Standard work moves at one-fifth the time without losing nuance.",
    },
    {
      icon: "FolderSearch",
      tag: "Due diligence",
      title: "M&A / fundraising due-diligence reviews",
      traditional: {
        how: "Team reads thousands of files in VDR — contracts, board minutes, IP, litigation, tax.",
        timeText: "300 hrs × 3 deals / quarter",
        volumeText: "≈ 100 hrs / month avg",
        hoursPerMonth: 300,
      },
      ai: {
        how: "Agent maps files to checklist, extracts key terms, flags red flags, drafts DD report.",
        timeText: "70 hrs × monthly avg",
        humanLoop: "Partner signs",
        hoursPerMonth: 70,
        toolCost: 12000,
      },
      feels: "Deal closure cycles shrink. Clients stop asking 'when will the report come?'",
    },
    {
      icon: "Library",
      tag: "Research",
      title: "Case-law research across SCC / Manupatra / IndianKanoon",
      traditional: {
        how: "Associate hunts through DBs, reads 30 judgements to find 4 useful ones.",
        timeText: "3 hrs × 100 queries / month",
        volumeText: "≈ 100",
        hoursPerMonth: 300,
      },
      ai: {
        how: "Agent searches multiple DBs, ranks judgements by relevance, drafts a research note with citations.",
        timeText: "20 min × 100",
        humanLoop: "Associate verifies citations",
        hoursPerMonth: 35,
        toolCost: 7500,
      },
      feels: "Your associates produce richer notes in less time. Partners notice.",
    },
    {
      icon: "Gavel",
      tag: "Court tracking",
      title: "Daily court listing & order pulls",
      traditional: {
        how: "Associates check cause-list portals every morning, copy orders, share with partners.",
        timeText: "1 hr / day × 25",
        volumeText: "monthly",
        hoursPerMonth: 25,
      },
      ai: {
        how: "Bot tracks cause-list across HCs / NCLT / DRT, fetches orders, summarises and pings the responsible partner.",
        timeText: "auto",
        humanLoop: "Associate reads summaries",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Nothing slips. Partners stop being woken at 7 AM by panicked clients.",
    },
    {
      icon: "FileText",
      tag: "Bundles",
      title: "Court bundle / paperbook creation",
      traditional: {
        how: "Para-legal compiles, paginates, indexes, prints bundles for hearings.",
        timeText: "8 hrs × 30 hearings / month",
        volumeText: "≈ 30",
        hoursPerMonth: 240,
      },
      ai: {
        how: "Tool ingests pleadings + exhibits, paginates, indexes, OCRs scanned docs, produces e-bundle.",
        timeText: "1 hr × 30",
        humanLoop: "Para-legal verifies",
        hoursPerMonth: 30,
        toolCost: 4500,
      },
      feels: "Para-legals stop pulling all-nighters before hearings.",
    },
    {
      icon: "FilePlus",
      tag: "Pleadings",
      title: "Pleadings & legal-notice drafting",
      traditional: {
        how: "Drafted from scratch using precedents, formatted manually.",
        timeText: "4 hrs × 40 / month",
        volumeText: "≈ 40",
        hoursPerMonth: 160,
      },
      ai: {
        how: "Agent drafts from facts + cause of action + relief; lawyer adds strategy and case-law.",
        timeText: "45 min × 40",
        humanLoop: "Lawyer signs",
        hoursPerMonth: 30,
        toolCost: 4500,
      },
      feels: "More volume per associate. Better consistency in firm style.",
    },
    {
      icon: "Calendar",
      tag: "Compliance",
      title: "Corporate / regulatory compliance calendar",
      traditional: {
        how: "Para-legal tracks RBI / SEBI / MCA / IBC dates manually for client portfolio.",
        timeText: "30 hrs / month",
        volumeText: "client roster",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Auto calendar pulls dates from regulations + filings, alerts owner, drafts filing checklists.",
        timeText: "auto",
        humanLoop: "Para-legal signs",
        hoursPerMonth: 5,
        toolCost: 2500,
      },
      feels: "Slips drop to zero. Compliance becomes a service line you can price.",
    },
    {
      icon: "Mail",
      tag: "Client comms",
      title: "Client status updates & matter summaries",
      traditional: {
        how: "Lawyer writes weekly update mails per matter.",
        timeText: "1.5 hrs / day × 25",
        volumeText: "monthly",
        hoursPerMonth: 37,
      },
      ai: {
        how: "Copilot drafts status update from matter activity; lawyer edits for tone.",
        timeText: "20 min / day",
        humanLoop: "Lawyer approves",
        hoursPerMonth: 8,
        toolCost: 2500,
      },
      feels: "Clients feel attended to without lawyers losing billable focus.",
    },
    {
      icon: "Users",
      tag: "KYC",
      title: "Client KYC, conflict & onboarding",
      traditional: {
        how: "Manual KYC + conflict check across past matters.",
        timeText: "60 min × 30 onboardings",
        volumeText: "≈ 30 / month",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Tool runs CKYC, beneficial-owner search, conflict check across firm DB.",
        timeText: "5 min × 30",
        humanLoop: "Partner signs",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Onboarding becomes invisible. Conflicts surface before, not after.",
    },
    {
      icon: "ClipboardList",
      tag: "Time-sheets",
      title: "Time-sheet capture & reconstruction",
      traditional: {
        how: "Lawyers reconstruct on 28th from calendar, mail, memory.",
        timeText: "4 hrs / lawyer / month × 12",
        volumeText: "12 lawyers",
        hoursPerMonth: 48,
      },
      ai: {
        how: "Auto-capture from calendar, mail, doc edits, court visits; lawyer edits/approves.",
        timeText: "20 min / lawyer / month",
        humanLoop: "Lawyer approves",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Realisation rate climbs because hours stop being lost.",
    },
    {
      icon: "Search",
      tag: "Discovery",
      title: "E-discovery & document review",
      traditional: {
        how: "Team reviews thousands of mails / files for privilege & relevance.",
        timeText: "200 hrs / matter × 1 active matter",
        volumeText: "monthly avg",
        hoursPerMonth: 200,
      },
      ai: {
        how: "Predictive coding + LLM tagging for relevance, privilege, hot docs; lawyers review highest-ranked first.",
        timeText: "40 hrs / matter",
        humanLoop: "Lawyer signs production",
        hoursPerMonth: 40,
        toolCost: 9000,
      },
      feels: "Litigation costs come down without sacrificing thoroughness.",
    },
    {
      icon: "ShieldCheck",
      tag: "Privacy",
      title: "DPDPA / privacy assessments & DPIAs",
      traditional: {
        how: "Privacy lawyer interviews business teams, drafts DPIA manually.",
        timeText: "20 hrs × 4 DPIAs / month",
        volumeText: "≈ 4",
        hoursPerMonth: 80,
      },
      ai: {
        how: "Agent runs DPIA questionnaire, maps to DPDPA obligations, drafts report; lawyer reviews.",
        timeText: "3 hrs × 4",
        humanLoop: "Lawyer signs",
        hoursPerMonth: 12,
        toolCost: 4500,
      },
      feels: "Privacy practice becomes a profitable service line, not a side project.",
    },
    {
      icon: "BookOpen",
      tag: "Knowledge",
      title: "Internal precedent / playbook search",
      traditional: {
        how: "Lawyers ask senior 'do we have a precedent for X?' — slow and inconsistent.",
        timeText: "scattered ≈ 30 hrs / month",
        volumeText: "across team",
        hoursPerMonth: 30,
      },
      ai: {
        how: "RAG over firm precedents, opinions, playbooks; lawyer asks in plain English.",
        timeText: "instant",
        humanLoop: "Senior for nuance",
        hoursPerMonth: 5,
        toolCost: 3000,
      },
      feels: "Junior lawyers stop reinventing wheels. Knowledge actually compounds.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Practice management dashboard for partners",
      traditional: {
        how: "Reports compiled monthly: WIP, billed, collected, realisation, utilisation.",
        timeText: "30 hrs / month",
        volumeText: "ops",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Live dashboard: WIP per matter, AR aging, lawyer utilisation, win rate; weekly partner digest.",
        timeText: "auto",
        humanLoop: "Partners decide",
        hoursPerMonth: 4,
        toolCost: 3000,
      },
      feels: "Partners run the firm with numbers, not hunches.",
    },
  ],
};

export default buildDomain(data);
