import { buildDomain } from "./_build";

const data = {
  slug: "logistics-freight",
  label: "Logistics & Freight",
  audience: "fleet owners, dispatchers & freight brokers",
  heroIcon: "Truck",
  headline: "Stop running your fleet on WhatsApp, Excel and 11 PM phone calls.",
  subheadline:
    "Dispatch, BOLs, PODs, detention claims, customer follow-ups — most of this is now an AI workflow, not a human shift. Below are the 15 leaks I plug for trucking and freight businesses, with the rupee value attached to each one.",
  chips: ["Dispatch AI", "BOL & POD extraction", "Detention claims", "Carrier matching", "Customer chat"],
  palette: { c1: "#3B82F6", c2: "#0EA5E9", accent: "#F59E0B" },
  assumedRate: 350,
  buildCost: 250000,
  monthlyRun: 9500,
  painHeadline:
    "You started a transport business — somewhere along the way you became a 24×7 call centre.",
  painPoints: [
    "Dispatchers retyping the same load info into 4 systems — TMS, Excel, WhatsApp, broker portals.",
    "Drivers calling at 2 AM because nobody knows which gate, which token number, which contact person.",
    "POD photos sitting in WhatsApp groups for 11 days before being filed — invoicing delayed, cash stuck.",
    "Detention and demurrage claims written off because nobody had time to email the proof on day 3.",
    "Same shipper asking 'where is my truck?' six times a day on three different channels.",
    "New customer onboarding takes 4 days because someone has to manually screenshot LR books, RC, insurance copies into your system.",
  ],
  tasks: [
    {
      icon: "Phone",
      tag: "Dispatch",
      title: "Manual load matching from broker emails & WhatsApp",
      traditional: {
        how: "Dispatcher reads 60+ broker emails and WhatsApp blasts, calls 5–8 carriers per load, scribbles numbers in a notebook, then enters into TMS.",
        timeText: "18 min × 10 loads/day",
        volumeText: "≈ 220 loads / month",
        hoursPerMonth: 66,
      },
      ai: {
        how: "AI agent ingests every inbound email and WA message, parses route, weight, rate, and matches against your historical carrier performance + current truck location. Drops a ranked shortlist into the dispatcher's screen with one-click assign.",
        timeText: "40 sec × 220 loads",
        humanLoop: "Dispatcher approves shortlist",
        hoursPerMonth: 10,
        toolCost: 5500,
      },
      feels: "The 7 AM scramble disappears. By the time you finish chai, the load board is half-assigned.",
    },
    {
      icon: "FileScan",
      tag: "Documents",
      title: "Extracting BOLs, LRs, e-way bills and rate confirmations",
      traditional: {
        how: "Operations team opens each PDF, copies consignor, consignee, GSTIN, freight, weight, vehicle no., HSN — into the order screen by hand.",
        timeText: "8 min × 18 docs/day",
        volumeText: "≈ 400 docs / month",
        hoursPerMonth: 53,
      },
      ai: {
        how: "Vision LLM reads any BOL / LR / rate-con / e-way bill, structures it, validates GSTIN against MCA, and pre-fills the order. Operator just clicks 'confirm'.",
        timeText: "12 sec × 400 docs",
        humanLoop: "Visual review before save",
        hoursPerMonth: 9,
        toolCost: 4200,
      },
      feels: "POD-to-invoice cycle drops from 11 days to under 48 hours. Working capital unlocks.",
    },
    {
      icon: "MessageCircle",
      tag: "Customer comms",
      title: "Answering 'where is my truck?' a hundred times a day",
      traditional: {
        how: "Customer service rep checks GPS portal, asks driver on WA, replies on email and WhatsApp, repeats for next caller.",
        timeText: "4 min × 80 queries/day",
        volumeText: "≈ 1,750 queries / month",
        hoursPerMonth: 117,
      },
      ai: {
        how: "WhatsApp + web chat agent reads live GPS, last gate-pass scan, ETA, and answers in the customer's language with proof images.",
        timeText: "instant",
        humanLoop: "Escalates only when truck is delayed > 2 hrs",
        hoursPerMonth: 18,
        toolCost: 6500,
      },
      feels: "Your CRM stops being a chat helpdesk. Big shippers actually compliment your tracking.",
    },
    {
      icon: "ClipboardCheck",
      tag: "POD",
      title: "Collecting and filing PODs from drivers",
      traditional: {
        how: "Driver clicks POD on phone, posts in WA group, accountant downloads, renames, uploads to portal, ticks Excel.",
        timeText: "9 min × 10 PODs/day",
        volumeText: "≈ 220 PODs / month",
        hoursPerMonth: 33,
      },
      ai: {
        how: "Driver sends POD to a single number — bot OCRs it, matches to LR, flags signature/stamp issues, files in your storage and triggers invoice.",
        timeText: "auto",
        humanLoop: "Only flagged PODs reviewed",
        hoursPerMonth: 5,
        toolCost: 3200,
      },
      feels: "Invoicing finally runs on time. CFO stops asking 'why is receivable so high'.",
    },
    {
      icon: "Receipt",
      tag: "Detention",
      title: "Filing detention & demurrage claims",
      traditional: {
        how: "Once a month, ops digs through GPS history, gate logs, emails, and writes claim PDFs — most slip past the deadline.",
        timeText: "35 min × 30 claims",
        volumeText: "≈ 30 claims / month",
        hoursPerMonth: 18,
      },
      ai: {
        how: "Agent watches GPS dwell-time, auto-builds the claim packet (timeline + photos + signed BOL), emails the shipper on day 2 with deadline math.",
        timeText: "auto + 5 min review",
        humanLoop: "Ops approves before send",
        hoursPerMonth: 3,
        toolCost: 2200,
      },
      feels: "Claims you used to write off now actually get paid. Pure recovered revenue.",
    },
    {
      icon: "UserPlus",
      tag: "Onboarding",
      title: "Onboarding a new shipper or carrier",
      traditional: {
        how: "Sales sends a Google Form, chases for KYC, GST, MSME, bank, sample LR — manual review, 4 days average.",
        timeText: "60 min × 12 onboardings",
        volumeText: "≈ 12 / month",
        hoursPerMonth: 12,
      },
      ai: {
        how: "Self-serve link, OCR-verified GST + PAN + RC + insurance, auto-checked against MCA21 / VAHAN, signed agreement via DigiLocker.",
        timeText: "8 min × 12",
        humanLoop: "Compliance officer signs off",
        hoursPerMonth: 2,
        toolCost: 1800,
      },
      feels: "You start a relationship with new shippers on day 1, not day 5.",
    },
    {
      icon: "MapPin",
      tag: "Routing",
      title: "Daily route & trip planning",
      traditional: {
        how: "Senior dispatcher mentally optimises 30 trucks, 80 stops, considering tolls, RTO restrictions, return loads.",
        timeText: "90 min/day",
        volumeText: "26 working days",
        hoursPerMonth: 39,
      },
      ai: {
        how: "Optimiser proposes routes with toll, fuel, return-load probability, RTO ban times — dispatcher just tweaks 2–3 outliers.",
        timeText: "12 min/day",
        humanLoop: "Manual override when needed",
        hoursPerMonth: 6,
        toolCost: 3500,
      },
      feels: "Empty miles drop noticeably. Dispatchers go home before sunset.",
    },
    {
      icon: "Banknote",
      tag: "Invoicing",
      title: "Generating customer invoices with proofs attached",
      traditional: {
        how: "Accounts pulls trip sheet, POD, fuel receipts, toll, detention proof, builds invoice PDF, emails customer.",
        timeText: "14 min × 220 invoices",
        volumeText: "≈ 220 / month",
        hoursPerMonth: 51,
      },
      ai: {
        how: "Once POD lands, system assembles the invoice + annexures + e-invoice IRN automatically, sends to AP contact, follows up.",
        timeText: "30 sec",
        humanLoop: "Edge cases reviewed",
        hoursPerMonth: 7,
        toolCost: 3800,
      },
      feels: "DSO drops by ~12 days. CFO smiles for the first time this quarter.",
    },
    {
      icon: "Bell",
      tag: "Follow-up",
      title: "Payment & receivable follow-ups",
      traditional: {
        how: "Junior calls and mails 50–80 pending parties weekly, often the same person three times.",
        timeText: "5 min × 60 calls × 4 weeks",
        volumeText: "≈ 240 calls / month",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Agent sends polite WA + email reminders on aging buckets, answers basic queries (PO number, GSTIN), escalates only at 60+ days.",
        timeText: "auto",
        humanLoop: "Personal call only at 60+ days",
        hoursPerMonth: 4,
        toolCost: 2200,
      },
      feels: "Your collections officer becomes a strategist, not a phone monkey.",
    },
    {
      icon: "ShieldCheck",
      tag: "Compliance",
      title: "Vehicle & driver compliance tracking",
      traditional: {
        how: "Excel reminders for FC, insurance, PUC, NP permit, driver license, badge — frequently missed, fines paid.",
        timeText: "scattered ~25 hrs/month",
        volumeText: "60 trucks × 6 docs",
        hoursPerMonth: 25,
      },
      ai: {
        how: "Doc store with auto-expiry watcher, pings driver/admin 30 / 7 / 1 days before, prevents trip allocation if expired.",
        timeText: "near-zero",
        humanLoop: "Renewals signed off by admin",
        hoursPerMonth: 4,
        toolCost: 1800,
      },
      feels: "Zero RTO fines this quarter. Insurance never lapses.",
    },
    {
      icon: "Fuel",
      tag: "Fuel & costs",
      title: "Fuel theft & mileage anomaly detection",
      traditional: {
        how: "Manager eye-balls fuel slips vs. trip km in Excel once a month, catches 1 in 5 anomalies.",
        timeText: "12 hrs / month",
        volumeText: "60 trucks",
        hoursPerMonth: 12,
      },
      ai: {
        how: "Model compares declared mileage vs. GPS km, fuel-card txns vs. tank capacity, flags drivers/pumps with abnormal patterns.",
        timeText: "auto",
        humanLoop: "Manager investigates flagged cases",
        hoursPerMonth: 2,
        toolCost: 1500,
      },
      feels: "You finally know which 4 trucks are leaking margin. Most fleets recover the build cost just from this.",
    },
    {
      icon: "Workflow",
      tag: "TMS sync",
      title: "Keeping TMS, accounting & shipper portals in sync",
      traditional: {
        how: "Same trip data entered into TMS, Tally, shipper portal — typos, duplicate entries, painful month-end reconciliation.",
        timeText: "3 min × 220 trips × 3 systems",
        volumeText: "660 entries / month",
        hoursPerMonth: 33,
      },
      ai: {
        how: "Single source of truth, integration agents push to Tally / Zoho Books and to each shipper's portal automatically.",
        timeText: "auto",
        humanLoop: "Reconciles only mismatches",
        hoursPerMonth: 5,
        toolCost: 3000,
      },
      feels: "Month-end closes in 2 days, not 9.",
    },
    {
      icon: "ClipboardList",
      tag: "RFQ",
      title: "Replying to shipper RFQs and tenders",
      traditional: {
        how: "Sales reads 25-page tender, builds rate matrix on Excel based on lane history, writes a proposal.",
        timeText: "180 min × 14 RFQs",
        volumeText: "≈ 14 / month",
        hoursPerMonth: 42,
      },
      ai: {
        how: "RFQ reader extracts lanes, vehicle types, requirements; pulls historic costs; drafts a priced proposal in your template.",
        timeText: "20 min × 14",
        humanLoop: "Sales reviews & negotiates",
        hoursPerMonth: 5,
        toolCost: 2400,
      },
      feels: "You bid on more tenders than your competitors — and win them with better-priced data.",
    },
    {
      icon: "Headphones",
      tag: "Driver support",
      title: "Driver helpdesk in regional languages",
      traditional: {
        how: "Office staff fields driver calls about diesel cards, gate passes, permits, ETA changes — half the calls in Punjabi/Bhojpuri.",
        timeText: "3 min × 90 calls/day",
        volumeText: "≈ 2,000 calls / month",
        hoursPerMonth: 100,
      },
      ai: {
        how: "Voice + WhatsApp agent in Hindi, Punjabi, Tamil — answers SOPs, raises tickets, escalates real emergencies to humans.",
        timeText: "instant",
        humanLoop: "Real emergencies routed to ops",
        hoursPerMonth: 18,
        toolCost: 7500,
      },
      feels: "Drivers feel supported. Office stops feeling like a 24×7 call centre.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Weekly P&L per truck / lane / customer",
      traditional: {
        how: "Analyst pulls reports from TMS, Tally, Excel sheets, builds pivot every Monday — owner reads it Wednesday, decisions on Friday.",
        timeText: "9 hrs/week",
        volumeText: "4 weeks",
        hoursPerMonth: 36,
      },
      ai: {
        how: "Live dashboard with per-truck profit, idle days, top loss-making lanes — owner gets a Monday WhatsApp summary in plain Hindi/English.",
        timeText: "auto",
        humanLoop: "Owner reads & decides",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "You stop running the business on gut. You actually know which lane to drop.",
    },
  ],
};

export default buildDomain(data);
