import { buildDomain } from "./_build";

const data = {
  slug: "manufacturing",
  label: "Manufacturing",
  audience: "plant heads, ops managers & SME promoters",
  heroIcon: "Factory",
  headline: "Your shop floor runs on tribal knowledge and paper. Both retire when your senior leaves.",
  subheadline:
    "From RFQ to dispatch, most Indian manufacturers still operate on Excel, paper job-cards and WhatsApp pings. Below are 15 places I bring AI into a plant — without ripping out your ERP — and the rupees each one returns.",
  chips: ["RFQ-to-quote", "Job-card AI", "QC vision", "Vendor reconciliation", "Maintenance"],
  palette: { c1: "#0EA5E9", c2: "#475569", accent: "#F97316" },
  assumedRate: 380,
  buildCost: 320000,
  monthlyRun: 12000,
  painHeadline:
    "Your most experienced engineer is a search engine. The day he leaves, the plant slows down.",
  painPoints: [
    "RFQs arrive as dirty PDFs, drawings, Excel — quotation engineer takes 2 days per quote.",
    "Job-cards on paper. Operators tick boxes. Nobody knows real OEE till month-end.",
    "QC reports are a stack of Excel sheets nobody analyses for trends.",
    "Vendor invoices reconciled by clerks against POs — short-shipments quietly accepted.",
    "Maintenance is reactive — machine stops, then panic, then ₹3L overtime.",
    "Customer complaints come over WhatsApp, never become tickets, never become root-cause.",
  ],
  tasks: [
    {
      icon: "FileSearch",
      tag: "RFQ",
      title: "RFQ intake, drawing reading & quote drafting",
      traditional: {
        how: "Sales engineer reads the drawing, looks up materials, asks shop for cycle time, builds Excel quote.",
        timeText: "5 hrs × 30 RFQs/month",
        volumeText: "≈ 30 RFQs",
        hoursPerMonth: 150,
      },
      ai: {
        how: "Agent reads drawing + spec PDF, identifies material/process, pulls historic costs of similar parts, drafts quote in your template.",
        timeText: "20 min × 30",
        humanLoop: "Sales engineer reviews & negotiates",
        hoursPerMonth: 12,
        toolCost: 6500,
      },
      feels: "Quote turn-around drops from 3 days to 4 hours. Win-rate climbs because you're first.",
    },
    {
      icon: "ClipboardList",
      tag: "Production",
      title: "Digital job-cards & live OEE",
      traditional: {
        how: "Supervisor prints job-cards, operators tick & sign; data entered to Excel weekly.",
        timeText: "15 hrs / week",
        volumeText: "4 weeks",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Tablet job-cards, voice updates from operators in Hindi, live OEE per machine, downtime auto-categorised.",
        timeText: "auto",
        humanLoop: "Supervisor confirms abnormal events",
        hoursPerMonth: 8,
        toolCost: 5000,
      },
      feels: "OEE becomes a number you act on Tuesday, not see Friday.",
    },
    {
      icon: "ShieldCheck",
      tag: "QC",
      title: "First-piece & in-process quality vision check",
      traditional: {
        how: "QC inspector measures samples with vernier, fills paper sheet, anomalies caught hours later.",
        timeText: "20 hrs / week",
        volumeText: "4 weeks",
        hoursPerMonth: 80,
      },
      ai: {
        how: "Camera + vision model checks dimensions, surface defects, label/printing; logs SPC charts; alerts on drift.",
        timeText: "auto",
        humanLoop: "QC investigates flagged units",
        hoursPerMonth: 14,
        toolCost: 7500,
      },
      feels: "Rejection rate drops. Customer complaints trend down for the first time in years.",
    },
    {
      icon: "Wrench",
      tag: "Maintenance",
      title: "Predictive maintenance from machine logs & audio",
      traditional: {
        how: "Maintenance is breakdown-driven; PM schedules ignored; ₹2-4L emergency calls every month.",
        timeText: "60 hrs / month firefighting",
        volumeText: "20 critical machines",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Vibration / current / sound sensors + model predicts failures 3-7 days early; auto raises work orders.",
        timeText: "auto",
        humanLoop: "Maintenance executes work orders",
        hoursPerMonth: 12,
        toolCost: 6500,
      },
      feels: "Unplanned downtime drops sharply. The plant feels less chaotic on Mondays.",
    },
    {
      icon: "Receipt",
      tag: "Vendor",
      title: "Vendor invoice ↔ PO ↔ GRN 3-way matching",
      traditional: {
        how: "Accounts clerk opens 3 PDFs, matches line by line, calls vendor for short shipments.",
        timeText: "12 min × 600 invoices",
        volumeText: "≈ 600 / month",
        hoursPerMonth: 120,
      },
      ai: {
        how: "Agent reads invoice, matches to PO and GRN at line level, drafts disputes for mismatches.",
        timeText: "1 min × 600",
        humanLoop: "Disputes confirmed by buyer",
        hoursPerMonth: 14,
        toolCost: 4500,
      },
      feels: "Short-shipments stop slipping past. Vendor payments get cleaner, faster.",
    },
    {
      icon: "Package",
      tag: "Stores",
      title: "Stores: receipts, indents, reorder points",
      traditional: {
        how: "Storekeeper writes indents in book, supervisor approves, buyer raises PO; stockouts common.",
        timeText: "40 hrs / month",
        volumeText: "1 store",
        hoursPerMonth: 40,
      },
      ai: {
        how: "Live BOM-driven reorder, visual stock counting via phone camera, indent approvals on WA.",
        timeText: "auto",
        humanLoop: "Buyer signs POs",
        hoursPerMonth: 6,
        toolCost: 3000,
      },
      feels: "Inventory days drop. Production never stops because of a missing washer.",
    },
    {
      icon: "Workflow",
      tag: "Planning",
      title: "Production planning & shop loading",
      traditional: {
        how: "Planner builds weekly plan in Excel, juggles changes via WA.",
        timeText: "20 hrs / week",
        volumeText: "4 weeks",
        hoursPerMonth: 80,
      },
      ai: {
        how: "Solver schedules orders against machines/setups, suggests changes when a hot order arrives.",
        timeText: "auto",
        humanLoop: "Planner accepts/edits",
        hoursPerMonth: 12,
        toolCost: 5500,
      },
      feels: "Customer commitments become realistic again. Less frantic re-planning.",
    },
    {
      icon: "Truck",
      tag: "Dispatch",
      title: "Dispatch documentation: invoice, e-way, packing list",
      traditional: {
        how: "Despatch clerk types invoice, packing list, e-way bill, transporter LR — multiple systems.",
        timeText: "18 min × 300 dispatches",
        volumeText: "≈ 300 / month",
        hoursPerMonth: 90,
      },
      ai: {
        how: "Single 'dispatch' button generates all docs, posts to GSTN, books transporter via API.",
        timeText: "auto + 2 min check",
        humanLoop: "Clerk signs",
        hoursPerMonth: 10,
        toolCost: 3500,
      },
      feels: "Dispatches don't pile up at 5 PM waiting for paperwork.",
    },
    {
      icon: "AlertCircle",
      tag: "Complaints",
      title: "Customer complaint capture & 8D / RCA",
      traditional: {
        how: "Complaints come on WA / phone — sales takes notes — RCA half-done.",
        timeText: "20 hrs / month",
        volumeText: "30 complaints",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Complaints captured via portal/WA, AI groups similar issues, drafts 5-Why + 8D from QC + production data.",
        timeText: "auto + review",
        humanLoop: "Quality head signs",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Repeat complaints fall. Big customers see you as a serious supplier.",
    },
    {
      icon: "FileText",
      tag: "Compliance",
      title: "ISO / IATF audit prep & document control",
      traditional: {
        how: "Once a year, team scrambles to update SOPs, records, training logs.",
        timeText: "120 hrs in audit month",
        volumeText: "amortise → 12 hrs/month avg",
        hoursPerMonth: 12,
      },
      ai: {
        how: "Living doc system tracks SOP changes, training records, internal audit findings; produces audit packets on demand.",
        timeText: "auto",
        humanLoop: "MR signs off",
        hoursPerMonth: 2,
        toolCost: 2200,
      },
      feels: "Audits stop being all-nighters. Findings drop year over year.",
    },
    {
      icon: "Activity",
      tag: "Energy",
      title: "Energy & utility cost tracking",
      traditional: {
        how: "Electrical engineer notes meter readings; analysis monthly.",
        timeText: "12 hrs / month",
        volumeText: "30 meters",
        hoursPerMonth: 12,
      },
      ai: {
        how: "Energy meter pull, kWh / unit produced tracked live, anomaly alerts on idle consumption.",
        timeText: "auto",
        humanLoop: "Engineer investigates spikes",
        hoursPerMonth: 2,
        toolCost: 2200,
      },
      feels: "Energy cost / unit drops measurably. SBI loan interview goes better.",
    },
    {
      icon: "BookOpen",
      tag: "Knowledge",
      title: "Internal SOP & troubleshooting bot for operators",
      traditional: {
        how: "New operator asks senior 'what to do?'; senior frustrated; mistakes happen on shift change.",
        timeText: "scattered ≈ 25 hrs / month",
        volumeText: "across plant",
        hoursPerMonth: 25,
      },
      ai: {
        how: "Voice bot in Hindi answers SOP / setup / common defect questions; logs unanswered ones for the trainer.",
        timeText: "instant",
        humanLoop: "Trainer feeds new SOPs",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Tribal knowledge becomes shared knowledge. Onboarding new operators gets way faster.",
    },
    {
      icon: "Mail",
      tag: "Sales",
      title: "Daily sales follow-ups with B2B customers",
      traditional: {
        how: "Sales engineer drafts mails for quote follow-ups, payment reminders, sample feedback.",
        timeText: "2 hrs / day × 25",
        volumeText: "1 sales engineer",
        hoursPerMonth: 50,
      },
      ai: {
        how: "Sales agent drafts personalised follow-ups using CRM context; sales engineer just reviews & sends.",
        timeText: "20 min/day",
        humanLoop: "Engineer approves before send",
        hoursPerMonth: 8,
        toolCost: 2500,
      },
      feels: "More open quotes get closed. Pipeline stops leaking through silence.",
    },
    {
      icon: "Banknote",
      tag: "Costing",
      title: "Per-part costing accuracy",
      traditional: {
        how: "Finance computes part-cost annually; market changes, costs are stale; bidding gets risky.",
        timeText: "60 hrs / quarter",
        volumeText: "amortise → 20 hrs / month",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Live cost engine combines material LME, energy, labour rate, scrap %, machine hour rate per part.",
        timeText: "auto",
        humanLoop: "Finance reviews monthly",
        hoursPerMonth: 4,
        toolCost: 3500,
      },
      feels: "You stop bidding low on parts that secretly bleed. Margin per part visible weekly.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Plant dashboard for promoter / MD",
      traditional: {
        how: "MD waits for monthly MIS PPT; surprises only after quarter close.",
        timeText: "25 hrs / month for MIS team",
        volumeText: "1 MIS team",
        hoursPerMonth: 25,
      },
      ai: {
        how: "Live dashboard with OEE, scrap %, on-time delivery, CM per product, AR aging — promoter gets daily WA summary.",
        timeText: "auto",
        humanLoop: "Promoter decides",
        hoursPerMonth: 4,
        toolCost: 3000,
      },
      feels: "Promoter walks the plant with numbers in hand, not asking 'how was last month?'",
    },
  ],
};

export default buildDomain(data);
