import { buildDomain } from "./_build";

const data = {
  slug: "real-estate",
  label: "Real Estate & Property Management",
  audience: "developers, brokers & property managers",
  heroIcon: "Building2",
  headline: "You've spent ₹40 lakh on lead generation. The leads are dying in your call team's WhatsApp.",
  subheadline:
    "From inquiry to site visit to booking to handover — Indian real estate is a leaking bucket of human time. These 15 AI plays plug the leaks for builders, channel partners and property managers.",
  chips: ["Lead qualification", "Site-visit booking", "Tenant management", "RERA compliance", "Handover ops"],
  palette: { c1: "#84CC16", c2: "#0D9488", accent: "#C2410C" },
  assumedRate: 350,
  buildCost: 220000,
  monthlyRun: 8500,
  painHeadline:
    "Three out of every four leads you bought never even got a real conversation back.",
  painPoints: [
    "Tele-callers can't keep up with leads from Meta, Magicbricks, 99acres, Housing.",
    "Brokers chase same leads in different channels — confusing the customer.",
    "Site visits booked without confirming intent, then no-shows on a Sunday.",
    "Channel-partner commission disputes consume managers every Friday.",
    "Tenants raise maintenance tickets on WA, then forgotten.",
    "RERA quarterly updates, OC handover docs, possession letters — manual nightmare.",
  ],
  tasks: [
    {
      icon: "Filter",
      tag: "Leads",
      title: "Lead qualification across portals & ads",
      traditional: {
        how: "Tele-caller calls every lead, asks budget, location, intent — most never answer.",
        timeText: "5 min × 200 leads/day",
        volumeText: "≈ 5,000 / month",
        hoursPerMonth: 416,
      },
      ai: {
        how: "WA + voice agent qualifies in under 60 sec, scores intent, books site visit only for hot leads.",
        timeText: "auto",
        humanLoop: "Sales calls hot leads",
        hoursPerMonth: 60,
        toolCost: 5500,
      },
      feels: "Cost per qualified lead drops 50%. Sales actually talks to buyers, not tyre-kickers.",
    },
    {
      icon: "CalendarCheck",
      tag: "Site visits",
      title: "Site visit booking & confirmation",
      traditional: {
        how: "Coordinator schedules slots, calls to confirm twice, no-shows still 35%.",
        timeText: "10 min × 30 visits/day",
        volumeText: "≈ 750 / month",
        hoursPerMonth: 125,
      },
      ai: {
        how: "Bot books slots based on host calendars, sends location + maps, reconfirms morning of visit, reschedules no-shows.",
        timeText: "auto",
        humanLoop: "Host hands over after visit",
        hoursPerMonth: 18,
        toolCost: 3000,
      },
      feels: "No-show rate falls to under 15%. Sundays at site become productive.",
    },
    {
      icon: "Camera",
      tag: "Walkthroughs",
      title: "Virtual tour & FAQ assistant",
      traditional: {
        how: "Sales rep does WhatsApp video calls and types floor-plan answers repeatedly.",
        timeText: "20 min × 100 leads/month",
        volumeText: "≈ 100",
        hoursPerMonth: 33,
      },
      ai: {
        how: "Interactive walkthrough chatbot with floor plans, prices, amenities, RERA details — 24×7.",
        timeText: "auto",
        humanLoop: "Sales for hot triggers",
        hoursPerMonth: 5,
        toolCost: 3500,
      },
      feels: "NRI buyers convert without ever stepping in. Cost per closing drops.",
    },
    {
      icon: "Receipt",
      tag: "Channel partners",
      title: "CP enrolment, lead claims & commission tracking",
      traditional: {
        how: "Builder team manages CP MOUs, lead duplication disputes, commission Excel.",
        timeText: "60 hrs / month",
        volumeText: "200 CPs",
        hoursPerMonth: 60,
      },
      ai: {
        how: "CP portal with single-source lead, auto-deduplication, commission calc on milestone, e-payments.",
        timeText: "auto",
        humanLoop: "Sales head signs payouts",
        hoursPerMonth: 8,
        toolCost: 4500,
      },
      feels: "CP disputes vanish. Best CPs send you more leads.",
    },
    {
      icon: "FileText",
      tag: "RERA",
      title: "RERA quarterly disclosures & filings",
      traditional: {
        how: "Compliance officer compiles construction status, finance, deeds quarterly.",
        timeText: "60 hrs / quarter / project × 5",
        volumeText: "amortise → 100 hrs / month",
        hoursPerMonth: 100,
      },
      ai: {
        how: "Agent pulls construction images, vendor payments, sales register; drafts RERA template.",
        timeText: "auto + 5 hr review",
        humanLoop: "Compliance signs",
        hoursPerMonth: 15,
        toolCost: 4500,
      },
      feels: "RERA filings stop dragging. Promoter sleeps better.",
    },
    {
      icon: "FileCheck",
      tag: "Booking docs",
      title: "Booking forms, ATS & registration paperwork",
      traditional: {
        how: "Sales fills booking form, ATS, KYC, payment plan — manual paperwork.",
        timeText: "90 min × 60 bookings/month",
        volumeText: "≈ 60",
        hoursPerMonth: 90,
      },
      ai: {
        how: "Digital booking flow with KYC, e-stamp, e-sign, ATS auto-generated; ready for sub-registrar.",
        timeText: "10 min × 60",
        humanLoop: "Sales reviews",
        hoursPerMonth: 10,
        toolCost: 4500,
      },
      feels: "Booking experience feels like a fintech, not a builder.",
    },
    {
      icon: "Wrench",
      tag: "Tenants",
      title: "Tenant maintenance ticket management",
      traditional: {
        how: "Society / PMC takes WA messages, calls vendor, often loses tickets.",
        timeText: "8 min × 25 tickets/day",
        volumeText: "≈ 600 / month",
        hoursPerMonth: 80,
      },
      ai: {
        how: "Tenant raises on WA bot, photo + voice; auto-assigns to vendor, tracks SLA, gets feedback.",
        timeText: "auto",
        humanLoop: "Manager handles disputes",
        hoursPerMonth: 14,
        toolCost: 3000,
      },
      feels: "Tenants stop posting in society WA group with angry rants.",
    },
    {
      icon: "Wallet",
      tag: "Rent",
      title: "Rent collection & late-fee enforcement",
      traditional: {
        how: "PMC manually tracks dues, calls late-payers, calculates late fee.",
        timeText: "30 hrs / month",
        volumeText: "300 units",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Auto-debit + UPI nudges, late-fee calc per agreement, escalations on aging.",
        timeText: "auto",
        humanLoop: "Manager handles disputes",
        hoursPerMonth: 5,
        toolCost: 2500,
      },
      feels: "Rent collection days drop. PMC team gets time for value-add.",
    },
    {
      icon: "ClipboardCheck",
      tag: "Audits",
      title: "Society / building inspection rounds",
      traditional: {
        how: "Manager walks every floor weekly, fills checklist on paper.",
        timeText: "8 hrs × 4 weeks",
        volumeText: "monthly",
        hoursPerMonth: 32,
      },
      ai: {
        how: "Manager uses phone app: photo + voice → auto-tagged checklist, vendor work-orders raised.",
        timeText: "2 hrs × 4",
        humanLoop: "Manager signs",
        hoursPerMonth: 8,
        toolCost: 2200,
      },
      feels: "Repairs happen before residents complain.",
    },
    {
      icon: "Megaphone",
      tag: "Marketing",
      title: "Local digital marketing creative for projects",
      traditional: {
        how: "Agency makes creatives in 2-week cycles; tests slow.",
        timeText: "30 hrs / month",
        volumeText: "marketing",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Generative engine produces variations of hero ads, neighbourhood ads, language variants.",
        timeText: "auto",
        humanLoop: "Marketing approves",
        hoursPerMonth: 6,
        toolCost: 4000,
      },
      feels: "Cost per qualified visit drops materially.",
    },
    {
      icon: "Bell",
      tag: "Customer journey",
      title: "Post-booking customer updates till possession",
      traditional: {
        how: "CRM team mails monthly construction updates; many customers feel ignored.",
        timeText: "30 hrs / month",
        volumeText: "CRM",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Personalised WA updates per booking with construction photos, milestone payments, expected possession.",
        timeText: "auto",
        humanLoop: "CRM handles questions",
        hoursPerMonth: 5,
        toolCost: 3000,
      },
      feels: "Customers refer friends instead of complaining online.",
    },
    {
      icon: "FileScan",
      tag: "Documents",
      title: "Khata, sale-deed, OC document handling",
      traditional: {
        how: "Legal team coordinates society OC, sale-deed registration, khata transfer per unit.",
        timeText: "5 hrs × 30 handovers / month",
        volumeText: "≈ 30",
        hoursPerMonth: 150,
      },
      ai: {
        how: "Agent pre-fills sale deed, e-stamp, prepares khata application; coordinates appointments.",
        timeText: "1 hr × 30",
        humanLoop: "Legal signs",
        hoursPerMonth: 30,
        toolCost: 5500,
      },
      feels: "Possession ceremonies actually happen on the promised date.",
    },
    {
      icon: "Search",
      tag: "Resale",
      title: "Resale & rental listing across portals",
      traditional: {
        how: "Broker uploads same listing to 99acres, Magicbricks, Housing — repeats all edits.",
        timeText: "20 min × 80 listings/month",
        volumeText: "≈ 80",
        hoursPerMonth: 27,
      },
      ai: {
        how: "Single-source listing pushed to all portals; AI writes descriptions; reposts on schedule.",
        timeText: "5 min × 80",
        humanLoop: "Broker reviews",
        hoursPerMonth: 7,
        toolCost: 1500,
      },
      feels: "Listings stay fresh. Inquiries quietly improve.",
    },
    {
      icon: "Sparkles",
      tag: "Pricing",
      title: "Project & unit dynamic pricing",
      traditional: {
        how: "Sales head decides discount per unit gut-feel, often inconsistent.",
        timeText: "15 hrs / month",
        volumeText: "sales head",
        hoursPerMonth: 15,
      },
      ai: {
        how: "Pricing model uses inventory aging, demand signals, competition; suggests floor & target prices.",
        timeText: "auto",
        humanLoop: "Sales head approves",
        hoursPerMonth: 3,
        toolCost: 2500,
      },
      feels: "You stop leaving lakhs on the table per booking.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "Daily sales & funnel dashboard",
      traditional: {
        how: "MIS prepares weekly sales review; stale by Monday.",
        timeText: "30 hrs / month",
        volumeText: "MIS",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Live dashboard: leads, MQL, SQL, visits, bookings, payments — daily WA digest to leadership.",
        timeText: "auto",
        humanLoop: "Leadership decides",
        hoursPerMonth: 4,
        toolCost: 2500,
      },
      feels: "Sales reviews stop being apologies. They become decisions.",
    },
  ],
};

export default buildDomain(data);
