import { buildDomain } from "./_build";

const data = {
  slug: "renewable-energy",
  label: "Renewable Energy & Solar",
  audience: "rooftop solar EPCs, IPPs, energy consultants",
  heroIcon: "Sun",
  headline: "You install panels in days. The paperwork takes months. AI fixes the paperwork.",
  subheadline:
    "From lead qualification to subsidy applications to DISCOM net-metering and O&M ticketing, AI compresses the bureaucracy that throttles solar adoption in India. Below are 15 plays I deploy for solar EPCs, IPPs and energy consultants.",
  chips: ["Site survey AI", "System sizing", "Subsidy paperwork", "DISCOM apps", "AMC / monitoring"],
  palette: { c1: "#14B8A6", c2: "#84CC16", accent: "#F59E0B" },
  assumedRate: 500,
  buildCost: 300000,
  monthlyRun: 11000,
  painHeadline:
    "You sell 100 systems / month. Your subsidy team is the bottleneck — not your installers.",
  painPoints: [
    "Lead qualification uneven; engineers visit unviable rooftops.",
    "System sizing done in Excel — quotes vary by sales rep.",
    "Subsidy applications under PM Surya Ghar take weeks.",
    "DISCOM net-metering apps stuck for 60-90 days.",
    "O&M tickets logged on WA, often forgotten.",
    "Generation reports promised to clients rarely sent.",
  ],
  tasks: [
    {
      icon: "MessageCircle",
      tag: "Leads",
      title: "Lead qualification & site shortlisting",
      traditional: {
        how: "Tele-callers ask roof type, bill, location; engineers still visit unviable sites.",
        timeText: "8 min × 100 leads/day",
        volumeText: "≈ 2,500 / month",
        hoursPerMonth: 333,
      },
      ai: {
        how: "Bot collects bill image, roof photo, location; AI computes preliminary viability & savings.",
        timeText: "auto",
        humanLoop: "Sales calls hot",
        hoursPerMonth: 50,
        toolCost: 5000,
      },
      feels: "Engineers visit only viable sites. Cost per closed system drops.",
    },
    {
      icon: "Camera",
      tag: "Site survey",
      title: "Rooftop survey from photos",
      traditional: {
        how: "Engineer site visit takes half a day; manual measurements.",
        timeText: "4 hrs × 200 surveys/month",
        volumeText: "≈ 200",
        hoursPerMonth: 800,
      },
      ai: {
        how: "AI estimates roof area, shading, tilt from drone / satellite + customer photos.",
        timeText: "30 min × 200",
        humanLoop: "Engineer confirms onsite",
        hoursPerMonth: 100,
        toolCost: 7500,
      },
      feels: "Survey cycle drops from days to hours.",
    },
    {
      icon: "Calculator",
      tag: "Sizing",
      title: "System sizing & quote",
      traditional: {
        how: "Sales engineer fills Excel sizing sheet; quotes inconsistent.",
        timeText: "1 hr × 200 quotes/month",
        volumeText: "≈ 200",
        hoursPerMonth: 200,
      },
      ai: {
        how: "Engine takes load, roof, tariff, subsidy; outputs system, BOM, quote, payback.",
        timeText: "10 min × 200",
        humanLoop: "Sales reviews",
        hoursPerMonth: 33,
        toolCost: 4500,
      },
      feels: "Quote-to-customer drops from days to minutes.",
    },
    {
      icon: "FileText",
      tag: "Subsidy",
      title: "Subsidy application (PM Surya Ghar)",
      traditional: {
        how: "Subsidy exec fills portal forms manually for each customer.",
        timeText: "2 hrs × 150 / month",
        volumeText: "≈ 150",
        hoursPerMonth: 300,
      },
      ai: {
        how: "Agent pre-fills forms, assembles docs, submits, tracks status, nudges customer for OTPs.",
        timeText: "20 min × 150",
        humanLoop: "Exec signs",
        hoursPerMonth: 50,
        toolCost: 5500,
      },
      feels: "Subsidy realisation accelerates by weeks. Cash flow eases.",
    },
    {
      icon: "Workflow",
      tag: "DISCOM",
      title: "DISCOM net-metering applications",
      traditional: {
        how: "Liaison officer files applications; chases for weeks.",
        timeText: "3 hrs × 150 / month",
        volumeText: "≈ 150",
        hoursPerMonth: 450,
      },
      ai: {
        how: "Agent fills DISCOM portal, attaches drawings & docs, tracks, escalates aging.",
        timeText: "30 min × 150",
        humanLoop: "Officer signs",
        hoursPerMonth: 75,
        toolCost: 5500,
      },
      feels: "Net-metering days fall from 90 to 30. Customer happiness climbs.",
    },
    {
      icon: "Truck",
      tag: "Procurement",
      title: "BOM procurement & vendor PO",
      traditional: {
        how: "Procurement team raises POs to multiple vendors per system.",
        timeText: "1 hr × 150 systems/month",
        volumeText: "≈ 150",
        hoursPerMonth: 150,
      },
      ai: {
        how: "Auto-PO from quote BOM; vendor matching by stock, price, lead time.",
        timeText: "10 min × 150",
        humanLoop: "Procurement signs",
        hoursPerMonth: 25,
        toolCost: 3500,
      },
      feels: "Stock-out delays drop. Cash tied in unused inventory shrinks.",
    },
    {
      icon: "HardHat",
      tag: "Crew dispatch",
      title: "Install-crew scheduling",
      traditional: {
        how: "Project manager assigns crews on WA / paper.",
        timeText: "30 hrs / month",
        volumeText: "PM",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Optimiser assigns crews by skill, geography, system size.",
        timeText: "auto + 5 hr",
        humanLoop: "PM approves",
        hoursPerMonth: 7,
        toolCost: 3500,
      },
      feels: "Installations / day climb without bigger team.",
    },
    {
      icon: "ClipboardCheck",
      tag: "Commissioning",
      title: "Commissioning checklist & handover",
      traditional: {
        how: "Engineer fills paper handover; signed photo sent on WA.",
        timeText: "1 hr × 150 systems",
        volumeText: "≈ 150",
        hoursPerMonth: 150,
      },
      ai: {
        how: "App captures photos, IV curves, tests; AI verifies; handover PDF auto-generated.",
        timeText: "15 min × 150",
        humanLoop: "Engineer signs",
        hoursPerMonth: 38,
        toolCost: 3500,
      },
      feels: "Commissioning quality consistent. Disputes drop.",
    },
    {
      icon: "Activity",
      tag: "Monitoring",
      title: "Generation monitoring & fault prediction",
      traditional: {
        how: "O&M engineer checks plant logs weekly; faults caught late.",
        timeText: "60 hrs / month",
        volumeText: "O&M",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Anomaly detection on inverter logs; predicts module / inverter faults.",
        timeText: "auto + 8 hr",
        humanLoop: "Engineer dispatched",
        hoursPerMonth: 12,
        toolCost: 4500,
      },
      feels: "Plant uptime climbs. Customer trust climbs.",
    },
    {
      icon: "Wrench",
      tag: "AMC tickets",
      title: "AMC ticketing & site dispatch",
      traditional: {
        how: "Customer messages WA; tickets get lost.",
        timeText: "5 min × 30 tickets/day",
        volumeText: "≈ 750 / month",
        hoursPerMonth: 62,
      },
      ai: {
        how: "WA bot logs ticket, requests photos, dispatches engineer with parts.",
        timeText: "auto",
        humanLoop: "Coordinator follows",
        hoursPerMonth: 9,
        toolCost: 3000,
      },
      feels: "AMC renewals climb because service is felt.",
    },
    {
      icon: "FileText",
      tag: "RFP",
      title: "B2B / commercial RFP responses",
      traditional: {
        how: "Sales team builds RFP responses for commercial roof tops manually.",
        timeText: "20 hrs × 8 RFPs/month",
        volumeText: "≈ 8",
        hoursPerMonth: 160,
      },
      ai: {
        how: "Agent reads RFP, drafts technical + commercial response from past wins.",
        timeText: "3 hrs × 8",
        humanLoop: "Sales signs",
        hoursPerMonth: 24,
        toolCost: 5000,
      },
      feels: "Win-rate climbs. Sales bandwidth doubles.",
    },
    {
      icon: "Wallet",
      tag: "Finance",
      title: "Loan / financing facilitation",
      traditional: {
        how: "Sales mentions financing options; conversion poor.",
        timeText: "scattered ≈ 30 hrs / month",
        volumeText: "sales",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Engine matches customer to finance partners, fills app, tracks sanction.",
        timeText: "auto + 5 hr",
        humanLoop: "Sales closes",
        hoursPerMonth: 7,
        toolCost: 3500,
      },
      feels: "Finance-attached deals climb. Average system size grows.",
    },
    {
      icon: "FileScan",
      tag: "RECs",
      title: "RECs / carbon-credit paperwork",
      traditional: {
        how: "Compliance team applies for RECs / IRECs manually for IPP / commercial.",
        timeText: "30 hrs / month",
        volumeText: "compliance",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Agent compiles generation, audits, submits applications, tracks issuance.",
        timeText: "auto + 5 hr",
        humanLoop: "Compliance signs",
        hoursPerMonth: 6,
        toolCost: 3000,
      },
      feels: "Extra revenue per MWh; reporting burden vanishes.",
    },
    {
      icon: "Globe",
      tag: "ESG",
      title: "ESG / sustainability reporting",
      traditional: {
        how: "Sustainability team builds GRI / BRSR reports manually.",
        timeText: "60 hrs / quarter",
        volumeText: "amortise → 20 hrs / month",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Agent assembles indicators from operations, drafts report sections.",
        timeText: "auto + 5 hr / month",
        humanLoop: "Sustainability head signs",
        hoursPerMonth: 5,
        toolCost: 3000,
      },
      feels: "BRSR submissions easier. Investor questions get crisp answers.",
    },
    {
      icon: "BarChart3",
      tag: "Dashboard",
      title: "Project & portfolio dashboard",
      traditional: {
        how: "Project office builds weekly status; insights stale.",
        timeText: "30 hrs / month",
        volumeText: "PMO",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Live dashboard: pipeline, installs, subsidies, DISCOM, O&M, financials — daily digest.",
        timeText: "auto",
        humanLoop: "CXO decides",
        hoursPerMonth: 4,
        toolCost: 3000,
      },
      feels: "Leadership leads with daily numbers; growth doesn't outpace operations.",
    },
  ],
};

export default buildDomain(data);
