import { buildDomain } from "./_build";

const data = {
  slug: "telecom-isp",
  label: "Telecom / ISP / Connectivity Providers",
  audience: "ISP founders, telecom NOCs & enterprise connectivity teams",
  heroIcon: "Radio",
  headline: "Your customer churn isn't because of network. It's because of how you handle the ticket about the network.",
  subheadline:
    "From plan recommendations to outage explanations to enterprise SLA reports, AI lets a small ops team deliver carrier-grade service. These are 15 telecom & ISP workflows I rebuild with AI for Indian operators.",
  chips: ["NOC copilot", "Customer chat", "Outage comms", "Field-tech AI", "SLA reporting"],
  palette: { c1: "#06B6D4", c2: "#7C3AED", accent: "#F59E0B" },
  assumedRate: 400,
  buildCost: 280000,
  monthlyRun: 11000,
  painHeadline:
    "You sell connectivity. Your customers experience confusion.",
  painPoints: [
    "Customers call NOC for outages — NOC has to repeat status 200 times.",
    "Field engineers spend 30% of the day on the phone, not on towers.",
    "Plan upgrades / downgrades take days because of manual back-end edits.",
    "Enterprise SLA reports compiled in Excel monthly — clients angry.",
    "Ticket categorisation done by humans; same ticket re-classified 3 times.",
    "Cable / fibre cuts identified late because alarms drown in noise.",
  ],
  tasks: [
    {
      icon: "PhoneIncoming",
      tag: "Customer chat",
      title: "Tier-1 customer support",
      traditional: {
        how: "CS reps handle plan info, slowness complaints, recharge issues, address change.",
        timeText: "4 min × 400 calls/day",
        volumeText: "≈ 10,000 / month",
        hoursPerMonth: 666,
      },
      ai: {
        how: "Voice + WA bot handles tier-1 with secure auth; escalates to humans for true outages or refunds.",
        timeText: "auto",
        humanLoop: "Tier-2 humans",
        hoursPerMonth: 100,
        toolCost: 8500,
      },
      feels: "Wait time drops from 6 min to instant. NPS climbs.",
    },
    {
      icon: "AlertTriangle",
      tag: "Outage comms",
      title: "Outage communication & ETA",
      traditional: {
        how: "NOC posts to social, mass SMS, but individual calls flood in.",
        timeText: "scattered ≈ 80 hrs / month",
        volumeText: "across team",
        hoursPerMonth: 80,
      },
      ai: {
        how: "When alarm fires, agent identifies impacted geos, sends per-customer message with cause + ETA on WA.",
        timeText: "auto",
        humanLoop: "NOC reviews critical comms",
        hoursPerMonth: 12,
        toolCost: 4500,
      },
      feels: "Customer rage subsides. Refund tickets fall.",
    },
    {
      icon: "Wrench",
      tag: "Field tech",
      title: "Field engineer dispatch & guidance",
      traditional: {
        how: "Dispatcher assigns tickets manually; tech drives to wrong tower.",
        timeText: "8 min × 80 dispatches/day",
        volumeText: "≈ 2,000 / month",
        hoursPerMonth: 267,
      },
      ai: {
        how: "Optimiser routes tech with ticket context, parts, history; AI assistant guides on-site troubleshooting.",
        timeText: "auto",
        humanLoop: "Dispatcher handles edge",
        hoursPerMonth: 40,
        toolCost: 6500,
      },
      feels: "First-time-fix climbs. Truck rolls per ticket falls.",
    },
    {
      icon: "Bell",
      tag: "Alarms",
      title: "NOC alarm correlation & noise reduction",
      traditional: {
        how: "Engineer chases every alarm; many false positives.",
        timeText: "15 hrs / shift × 30",
        volumeText: "≈ 450 hrs",
        hoursPerMonth: 450,
      },
      ai: {
        how: "Correlation engine groups alarms by root cause, suggests action, suppresses noise.",
        timeText: "auto",
        humanLoop: "Engineer acts on root cause",
        hoursPerMonth: 80,
        toolCost: 8500,
      },
      feels: "MTTR drops sharply. Engineers stop burning out on noise.",
    },
    {
      icon: "Workflow",
      tag: "Plan changes",
      title: "Plan upgrade / downgrade / port-in",
      traditional: {
        how: "CS rep manually edits CRM, billing, IPTV — multi-system juggle.",
        timeText: "8 min × 200 changes/day",
        volumeText: "≈ 5,000 / month",
        hoursPerMonth: 666,
      },
      ai: {
        how: "Self-serve flow with auth; AI executes across systems and confirms.",
        timeText: "auto",
        humanLoop: "Humans for billing edge",
        hoursPerMonth: 100,
        toolCost: 6500,
      },
      feels: "Customers get changes in minutes, not days.",
    },
    {
      icon: "FileText",
      tag: "Enterprise SLA",
      title: "Enterprise SLA reports",
      traditional: {
        how: "Account manager compiles uptime + ticket reports per client monthly.",
        timeText: "4 hrs × 40 enterprise clients",
        volumeText: "monthly",
        hoursPerMonth: 160,
      },
      ai: {
        how: "Auto SLA report from probes + tickets + maintenance windows; sent to client.",
        timeText: "auto + 1 hr review",
        humanLoop: "Account manager signs",
        hoursPerMonth: 18,
        toolCost: 5000,
      },
      feels: "Clients renew because reports are credible and timely.",
    },
    {
      icon: "MapPin",
      tag: "Network planning",
      title: "Local growth / coverage planning",
      traditional: {
        how: "Planner uses Excel + maps to plan new POPs / towers.",
        timeText: "60 hrs / month",
        volumeText: "planning",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Demand model overlays leads, churn, competition, civic permissions; suggests sites.",
        timeText: "auto + review",
        humanLoop: "CTO signs site list",
        hoursPerMonth: 10,
        toolCost: 5500,
      },
      feels: "Capex goes where ARPU actually lives.",
    },
    {
      icon: "ShieldCheck",
      tag: "Compliance",
      title: "DOT / TRAI compliance reporting",
      traditional: {
        how: "Compliance officer prepares filings manually.",
        timeText: "30 hrs / month",
        volumeText: "compliance",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Engine pulls usage / quality / fault data, drafts filings, alerts owners.",
        timeText: "auto + 5 hr",
        humanLoop: "Compliance signs",
        hoursPerMonth: 6,
        toolCost: 3000,
      },
      feels: "Penalty notices stop. Audits get easier.",
    },
    {
      icon: "Wallet",
      tag: "Billing",
      title: "Bill disputes & adjustments",
      traditional: {
        how: "CS rep checks usage logs, computes prorated refunds, adjusts bill.",
        timeText: "10 min × 100 disputes/day",
        volumeText: "≈ 2,500 / month",
        hoursPerMonth: 416,
      },
      ai: {
        how: "Agent investigates dispute against usage logs, drafts adjustment with explanation.",
        timeText: "auto + 2 min review",
        humanLoop: "Supervisor approves > ₹X",
        hoursPerMonth: 60,
        toolCost: 5000,
      },
      feels: "Disputes close in minutes, not weeks. Trust metrics climb.",
    },
    {
      icon: "Megaphone",
      tag: "Acquisition",
      title: "Local lead capture & onboarding",
      traditional: {
        how: "Tele-callers convert leads from ads / referrals; many lost in week 1.",
        timeText: "4 min × 150 leads/day",
        volumeText: "≈ 3,750 / month",
        hoursPerMonth: 250,
      },
      ai: {
        how: "WA agent qualifies, books install, sends e-KYC + payment link, hands off only confirmed.",
        timeText: "auto",
        humanLoop: "Sales for high-ARPU plans",
        hoursPerMonth: 40,
        toolCost: 5000,
      },
      feels: "Cost per new connection drops. Time to first revenue shrinks.",
    },
    {
      icon: "Activity",
      tag: "Quality",
      title: "Per-customer link quality monitoring",
      traditional: {
        how: "Engineer eye-balls dashboards; many silent QoS drops missed.",
        timeText: "15 hrs / week",
        volumeText: "4 weeks",
        hoursPerMonth: 60,
      },
      ai: {
        how: "Anomaly detection on per-link RX/TX/loss, drafts proactive alert + free credit.",
        timeText: "auto",
        humanLoop: "Engineer acts on real issues",
        hoursPerMonth: 8,
        toolCost: 4000,
      },
      feels: "Customers find out you fixed it before they noticed it broke.",
    },
    {
      icon: "Mail",
      tag: "Renewals",
      title: "Renewal & winback campaigns",
      traditional: {
        how: "Marketing sends generic offers; conversion poor.",
        timeText: "20 hrs / month",
        volumeText: "marketing",
        hoursPerMonth: 20,
      },
      ai: {
        how: "Personalised offers per usage, NPS, payment history; tracked and tuned.",
        timeText: "auto",
        humanLoop: "Marketing reviews",
        hoursPerMonth: 4,
        toolCost: 3500,
      },
      feels: "Churn drops by a few points. Revenue compounds.",
    },
    {
      icon: "BookOpenCheck",
      tag: "Knowledge",
      title: "Internal NOC / field engineer Q&A bot",
      traditional: {
        how: "Junior engineers call seniors for OLT, ONT, BNG, OSPF questions at night.",
        timeText: "scattered ≈ 40 hrs / month",
        volumeText: "across team",
        hoursPerMonth: 40,
      },
      ai: {
        how: "RAG bot trained on vendor docs, RFCs, SOPs; cited answers in seconds.",
        timeText: "instant",
        humanLoop: "Seniors for nuance",
        hoursPerMonth: 6,
        toolCost: 3500,
      },
      feels: "Night-shift quality stops depending on who is on duty.",
    },
    {
      icon: "FileSearch",
      tag: "Vendor",
      title: "Vendor RFP & rate-card analysis",
      traditional: {
        how: "Procurement evaluates vendor quotes, builds comparison.",
        timeText: "20 hrs × 4 RFPs/quarter",
        volumeText: "amortise → 27 hrs / month",
        hoursPerMonth: 27,
      },
      ai: {
        how: "Agent extracts line items, normalises specs, builds TCO comparison.",
        timeText: "3 hrs × 4 / quarter",
        humanLoop: "Procurement signs",
        hoursPerMonth: 4,
        toolCost: 3000,
      },
      feels: "You buy smarter, faster.",
    },
    {
      icon: "BarChart3",
      tag: "Analytics",
      title: "CXO live dashboard",
      traditional: {
        how: "MIS pulls reports weekly; CXO acts late.",
        timeText: "30 hrs / month",
        volumeText: "MIS",
        hoursPerMonth: 30,
      },
      ai: {
        how: "Live dashboard: ARPU, churn, MTTR, NPS, ticket SLA — daily WA digest.",
        timeText: "auto",
        humanLoop: "CXO decides",
        hoursPerMonth: 4,
        toolCost: 3000,
      },
      feels: "CXO leads with daily numbers, not monthly surprises.",
    },
  ],
};

export default buildDomain(data);
